### ISSUE TITLE
[feat] 是不是考虑优化一下启动速度，暂时太慢了

### ISSUE THREAD

**Issue by kickTiger** [edonyzpc/personal-assistant#77]
这是我的插件启动速度：
![image](https://user-images.githubusercontent.com/3623068/235595315-a7254fe3-78a0-46b7-830d-afbdde9e89da.png)

可以看到personal-assistant是dataview的速度很多倍，10倍了。
能否优化这一块，加快启动速度。也在50左右？

我好把所有的插件启动速度控制在1000以下😄
![image](https://user-images.githubusercontent.com/3623068/235596434-ba006330-bd8f-4d9b-aaca-fbca7158e4e5.png)

我实验了好多回，都是差不多这个启动速度

**Comment by edonyzpc** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/7744664/235825119-736932ec-7e2c-4e41-b169-afb94cf66f0b.png">

我本地测试结果跟你的有出入，是否可以提供一下你的测试环境的参数：
```
- Obsidian Version: 
- Personal Assistant Version: 
- Plugin List: 
    - ...
- Console Log: 
```

**Comment by kickTiger** [comment]
我的电脑系统是：window10 64 LTSC
obsidian的版本一直是最新版
电脑性能的话，应该没啥问题，AMD Ryzen 7 5800X 8-Core,32G内存,6G显存
obsidian的主题是默认主题，安装了92个插件，启用了60个

多测试了几次
![image](https://user-images.githubusercontent.com/3623068/235829733-836744ec-2b3d-4d68-8a5a-7ac465ae5797.png)

![image](https://user-images.githubusercontent.com/3623068/235830617-37d3758d-2f60-4196-a5b2-44f63c4f5959.png)
![image](https://user-images.githubusercontent.com/3623068/235830636-93ea536e-04dd-4329-a44f-64a43b1a751e.png)


```js
Obsidian Developer Console
ObsidianOutlinerPlugin.ts:44 Loading obsidian-outliner
plugin:obsidian42-brat:23 loading Obsidian42 - BRAT
plugin:obsidian-tasks-plugin:221 loading plugin "tasks"
main.ts:16 loading obsidian-image-toolkit plugin v1.3.1 ...
plugin:obsidian-hypothesis-plugin:2 loading plugin 2023/5/3 11:54:35
plugin:obsidian-hypothesis-plugin:2 Start syncing...
main.ts:11 Loading Min3ditorHotkeys plugin
main.ts:13 Clear Unused Images plugin loaded...
plugin:obsidian-banners:28 Loading Banners...
plugin:homepage:2 Homepage: homepage (method: Replace all open notes, view: Default view, kind: Workspace)
plugin:Enhanced-editing:134 加载增强编辑插件
plugin:quickadd:17251 Loading QuickAdd
plugin:quickadd:15512 QuickAdd: (LOG) No migrations to run.
main.ts:7 Loading plugin FilePathToUri...
main.ts:17 loading url-into-selection
plugin:obsidian-admonition:479 Obsidian Admonition loaded
main.ts:235 Recent Files: Loading plugin v1.3.5
main.ts:291 Recent Files: maxLength is not set, using default (50)
main.ts:119 Dataview: version 0.5.55 (requires obsidian 0.13.11)
plugin:obsidian-local-rest-api:47287 REST API listening on https://127.0.0.1:27124/
plugin:obsidian-local-rest-api:47295 REST API listening on http://127.0.0.1:27123/
main.ts:41 timeline load
main.ts:124 cMenuToolbar v2.3.1 loaded
plugin:open-vscode:132 Loading Open vault in VSCode plugin
main.ts:213 Loading Number Headings Plugin, version 1.13.0
plugin:longform:37057 [Longform] Starting Longform 2.0.3…
plugin:media-extended:28 loading media-extended
mxbili-main.ts:44 loading MxBili
logger.js:47 [HPM] Proxy created: /  -> http://www.example.org
logger.js:47 [HPM] Proxy rewrite rule created: "^/fake/.+?/" ~> "/"
main.ts:20 Loading natural language date parser plugin
main.ts:30 loading markdown-table-editor plugin
plugin:metaedit:5434 Loading MetaEdit
plugin:metaedit:5191 MetaEdit: (LOG) automator of type 'KanbanHelper' does not exist.
plugin:metaedit:5191 MetaEdit: (LOG) automator of type 'ProgressProperties' does not exist.
app.js:1 Total plugin setup: 1,351ms
personal-assistant: 433ms
mx-bili-plugin: 95ms
obsidian-emoji-toolbar: 86ms
obsidian-plugin-update-tracker: 77ms
obsidian-local-rest-api: 49ms
obsidian-projects: 48ms
dataview: 47ms
obsidian-local-images: 44ms
media-extended: 34ms
obsidian-admonition: 32ms
table-editor-obsidian: 31ms
obsidian-tasks-plugin: 30ms
obsidian-hypothesis-plugin: 28ms
longform: 24ms
todoist-sync-plugin: 24ms
obsidian-quiet-outline: 21ms
markdown-table-editor: 19ms
obsidian-outliner: 19ms
obsidian-banners: 18ms
obsidian-html-plugin: 18ms
nldates-obsidian: 17ms
templater-obsidian: 12ms
quickadd: 12ms
better-word-count: 12ms
obsidian-advanced-uri: 11ms
editing-toolbar: 11ms
obsidian-task-archiver: 9ms
obsidian-image-toolkit: 8ms
various-complements: 8ms
Enhanced-editing: 7ms
buttons: 7ms
cmdr: 6ms
auto-note-mover: 5ms
open-vscode: 5ms
darlal-switcher-plus: 5ms
tag-wrangler: 4ms
workspaces-plus: 4ms
metaedit: 4ms
calendar: 4ms
obsidian42-brat: 3ms
homepage: 3ms
recent-files-obsidian: 3ms
number-headings-obsidian: 3ms
oz-clear-unused-images: 2ms
url-into-selection: 2ms
obsidian-view-mode-by-frontmatter: 2ms
open-weather: 2ms
obsidian-min3ditorhotkeys-plugin: 1ms
obsidian-file-path-to-uri: 1ms
obsidian-timeline: 1ms
reveal-active-file-button: 1ms
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'children')
    at t.createLeafInParent (app.js:1:1892723)
    at t.getUnpinnedLeaf (app.js:1:1894466)
    at t.getLeaf (app.js:1:1894676)
    at e.<anonymous> (app.js:1:2277981)
    at app.js:1:235927
    at Object.next (app.js:1:236032)
    at a (app.js:1:234750)
plugin:obsidian-hypothesis-plugin:2 StartAutoSync: this.timeoutIDAutoSync 209 with 10 minutes
plugin:longform:35569 [Longform] Loaded and watching projects. Found 37 drafts in 1.051s.
index.ts:153 Dataview: all 1090 files have been indexed in 1.822s (1090 cached, 0 skipped).
plugin:Enhanced-editing:817 附件目录
attachments
plugin:media-extended:13 youtube video url not supported or invalid
plugin:media-extended:13 bilibili video url not supported or invalid
plugin:obsidian42-brat:18 BRAT: Checking for plugin updates STARTED
plugin:obsidian42-brat:18 BRAT: Checking for plugin updates COMPLETED
```

**Comment by edonyzpc** [comment]
我先尝试本地复现一下

**Comment by Eli-Ven** [comment]
你好，不好意思想问一个无关的问题：你们是怎么查看插件启动速度的？我在社区和谷歌都没有搜到相关方案或插件，在Developer Tools - Console 也没有找到相关内容

**Comment by kickTiger** [comment]
设置,第三方插件,显示启动时间,重启查看

更详细的看控制台

**Comment by Eli-Ven** [comment]
> 设置,第三方插件,显示启动时间,重启查看
> 
> 更详细的看控制台

谢谢！

**Comment by edonyzpc** [comment]
这个问题我怀疑是全局 [observer:line39](https://github.com/edonyzpc/personal-assistant/blob/10b96af10b5511649dbaa2a6c9374e285c085365/src/plugin.ts#L39) 导致，不过我不知道什么原因会触发启动时间增加🤔
